### ISSUE TITLE
TooManyEmotes Bug

### ISSUE THREAD

**Issue by Cookie-Kurokami** [killfrenzy96/LCThirdPerson#3]
Starting in version 1.0.22 of LCThirdPersonFork, using TooManyEmotes's First Person Emotes and Move While Emoting features in combination with third person mode results in the camera repositioning itself inside of the player, rather than remaining behind.

Video showcasing the bug:
https://streamable.com/s1gcbr

How it worked in 1.0.21 and all versions prior, including the original LCThirdPerson mod:
https://streamable.com/hpa6vh

**Comment by killfrenzy96** [comment]
That doesn't look right. I'll take a look at this.

Currently, the mod disables itself if TooManyEmotes is active. This allows TooManyEmotes to take full control of the camera.

It is expected that when enabling first person in TooManyEmotes, the camera should go to first person. However, the part where you see the inside of your head is definitely a bug.

**Comment by killfrenzy96** [comment]
Fixed in 1.0.23: The inside of your head will no longer be visible when using first person emotes while in third person view.

However, the part where the camera goes first person when emoting in TooManyEmotes while first person emotes is enabled is intended behavior.

Further improvements could involve a config setting to maintain the older behavior, or instead a feature to automatically synchronize the TooManyEmotes first person setting with the third person toggle.

**Comment by Cookie-Kurokami** [comment]
Upon updating to 1.0.23, it would appear that the bug is in fact still persisting:
https://streamable.com/kooh8s

Perhaps reverting to the old behavior would be best? After all, the First Person Emotes setting already did function the way it was intended when used while actually in first person. Here's a clip showcasing this in version 1.0.21:
https://streamable.com/uty8v8

And here it is again, but with the Move While Emoting setting turned off, allowing the camera to smoothly and steadily track the movement of the player head:
https://streamable.com/a57yuj

For comparison, here's how that looks in 1.0.23:
https://streamable.com/3wgg9y

**Comment by Cookie-Kurokami** [comment]
I can also confirm that the issue persists even after the removal of all mods with the exception of BepInEx, TooManyEmotes, and LCThirdPersonFork. In fact, it's even worse, as the first person POV is completely obscured by the presence of the player head regardless of whether or not emotes are being used:
https://streamable.com/j4lw41

**Comment by killfrenzy96** [comment]
Ah yeah, something is definitely wrong. Somehow this version worked with my mods setup, but not with a minimal setup. I'll consider reverting, but I'd like to properly fix the underlying issue first.

**Comment by killfrenzy96** [comment]
Okay, the new issue may actually be unrelated to TooManyEmotes, where the `OriginalCullingMask` somehow reads a modified value. I have no idea why this behavior is different between my minimal and full mod setup, but I'm uploading an update that should resolve this problem completely.

I'll keep this issue open for now. Please let me know if 1.0.24 comes with any further issues.

**Comment by Cookie-Kurokami** [comment]
It appears the issue has only been partially circumvented, rather than actually fixed. In a minimal setup like the one I tested previously, using an emote while First Person Emotes is enabled does indeed force the camera out of third person and into first person as you intended. However, pressing the perspective change key again immediately reintroduces the visual bug this thread is about:
https://streamable.com/ut3igm

On my other, much less minimal mod setup though, the visual bug is present right off the bat upon emoting, though it is still able to be toggled on and off with the perspective change key:
https://streamable.com/g8chq6

Giving my own two cents here, but I really do think it would be best to simply restore the old behavior, especially with the bugs introduced by the attempts to change it. And that aside, I actually quite liked the way it functioned previously, with the camera behind the player as they emoted while in third person and switching to their POV only when they pressed the perspective change key again.

**Comment by killfrenzy96** [comment]
I have just tested 1.0.21, and it currently exhibits this behavior with a minimal mod setup:
https://streamable.com/5k4ks7

This is what occurs with a partial revert (disabling TooManyEmotes compatibility fixes):
https://streamable.com/bi3q77

Therefore, I don't think a revert would result in the wanted bug-free behavior.

I have worked on a proper fix. I am also aware that you liked how it functioned previously (and I also think that behavior would be better), so I have also allowed the third person camera to be active during a TooManyEmotes first person camera (the best of both worlds):
https://streamable.com/xhtym7

I am just doing some more testing on this patch before uploading it. You should be able to test it soon.

**Comment by killfrenzy96** [comment]
1.0.25 has been uploaded. Let me know if there are issues with the mod under your setup.

**Comment by Cookie-Kurokami** [comment]
As of 1.0.25, everything appears to be working perfectly. Thank you.
